### ISSUE TITLE
Problem with wav Files in Mavericks

### ISSUE THREAD

**Issue by deejal10** [nulloy/nulloy#73] opened 2015-08-09 20:02 UTC
![screenshot 2015-08-09 21 52 57](https://cloud.githubusercontent.com/assets/13237521/9156649/88faa4da-3ee1-11e5-83f8-3229ee74e048.png)
 
Some problems playing wav samples. I can't understand why :(

**Comment by noscript** [comment] 2015-08-09 20:28
I think this is duplicate of #70. Please try https://github.com/nulloy/nulloy/releases/download/0.8-autosink-fix/Nulloy-0.8-autosink-fix-universal.dmg

**Comment by deejal10** [comment] 2015-08-09 21:27
I works perfect!!! Great job :) 

Thousand thanks!

**Comment by noscript** [comment] 2015-08-09 23:03
Great. I will include the fix in the next release.

**Closed by noscript** 2015-08-09 23:03 UTC
